### PR TITLE
Existing game controller and model 

### PR DESCRIPTION
**Pull request by fredosantana**
Authentication added tool

### CODE REVIEW

**Comment by fredosantana** [comment]
Also still trying to figure out that readme conflict.

**Comment by kenmazaika** [comment]
Hi Wil -

Couple problems exist in this, largely my fault as I did a poor job communicating.  First there continue to be merge conflicts that need to be resolved.  Review this lesson on how to resolve them.
http://www.thefirehoseproject.com/advanced-git-topics/5

Also, your issue is blocked by the issue of creating a games table in the database (meaning you cannot do it, until a different team member does that task), which @katschre is working on in #5.

We discussed this stuff on the call last Thursday, but I think I forgot to share the recording.  That's my bad, I'm sorry.

Checkout this video recording:
https://vimeo.com/165629930

Password is: FIREHOSE

Once Katrina gets the game model up and working (and we get devise working), your ticket is to populate the user id's from the existing database table `games` (not build a new one called existing games).

I did a poor job explaining what was expected of you for this ticket, and I apologize.  My suggestion is to first make a pull request without merge conflicts that adds you to the contributors file first.  Wait for that change to be accepted into the main codebase before working on a second one.

Once we get that pull request merged in, we can work on getting you on track for this feature (after Katrina finishes hers).  Apologies for the miscommunication on my part.

**Comment by fredosantana** [comment]
It's cool Ken. Guess I jumped the gun on that one. I'll check out last week's video and fix the merge conflict before Thursday.

**Comment by kenmazaika** [comment]
Perfect!

**Pull request closed without merging**
